spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pzb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

beetl:
  templatesPath: templates



